GameCave/urls.py
from django.contrib import admin
from django.urls import path
from GamersCave import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('add_user/', views.RegisterUserView.as_view()),
    path('user/<int:user_id>/', views.UserView.as_view()),
    path('login/', views.LoginUserView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path('add_studio/', views.AddStudioView.as_view()),
    path('studio/<int:studio_id>/', views.StudioView.as_view()),
    path('all_studios/', views.AllStudioView.as_view()),
    path('add_game/', views.AddGameView.as_view()),
    path('game/<int:game_id>/', views.GameView.as_view()),
    path('all_games/', views.AllGameView.as_view()),
    path('add_article/', views.AddArticleView.as_view()),
    path('all_articles/', views.AllArticleView.as_view()),
    path('gamecave/forum/', views.ForumView.as_view()),
    path('gamecave/forum/addpost/', views.ForumPostAddView.as_view()),
    path('gamecave/forum/<int:forum_post_id>/', views.ForumPostView.as_view()),


]

__pycache__/GameCave/urls.py
from django.contrib import admin
from django.urls import path
from GamersCave import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('add_user/', views.RegisterUserView.as_view()),
    path('user/<int:user_id>/', views.UserView.as_view()),
    path('login/', views.LoginUserView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path('add_studio/', views.AddStudioView.as_view()),
    path('studio/<int:studio_id>/', views.StudioView.as_view()),
    path('all_studios/', views.AllStudioView.as_view()),
    path('add_game/', views.AddGameView.as_view()),
    path('game/<int:game_id>/', views.GameView.as_view()),
    path('all_games/', views.AllGameView.as_view()),
    path('add_article/', views.AddArticleView.as_view()),
    path('all_articles/', views.AllArticleView.as_view()),
    path('gamecave/forum/', views.ForumView.as_view()),
    path('gamecave/forum/addpost/', views.ForumPostAddView.as_view()),
    path('gamecave/forum/<int:forum_post_id>/', views.ForumPostView.as_view()),


]

GamersCave/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Studio(models.Model):
    name = models.CharField(max_length=100, unique=True)
    is_active = models.BooleanField(null=True)


class Game(models.Model):
    name = models.CharField(max_length=100, unique=True)
    year = models.IntegerField()
    description = models.TextField()
    studio = models.ForeignKey('Studio', on_delete=models.CASCADE)
    rates = models.ManyToManyField(User, through="GameRating")


class GameRating(models.Model):
    RATES = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5"),
        (6, "6"),
        (7, "7"),
        (8, "8"),
        (9, "9"),
        (10, "10"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    rate = models.IntegerField(choices=RATES)
    reviev = models.TextField(null=True)


class Article(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    by_user = models.ForeignKey(User, on_delete=models.CASCADE)


class Forum_post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class Post_answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Forum_post, on_delete=models.CASCADE, null=True)

templates/add_game.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
        Nazwa gry:<br>{{form.name}}<br>
        Rok produkcji:<br>{{form.year}}<br>
        Opis(opcjonalne)<br>{{form.description}}<br>
        Studio:<br>{{form.studio}}<br><br>
    <input type="submit">
    </form>
{% endblock %}

templates/add_studio.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
        Nazwa studia:<br>{{form.name}}<br>
        Czy studio wciąż funcjonuje?:<br>{{form.is_active}}<br><br>
    <input type="submit">
    </form>
{% endblock %}

templates/add_user.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
        {{ msg }}<br>
        <label for ="username">Type your username: </label><input type="text" name="username" id="username"><br>
        <label for ="password">Type your password: </label><input type="password" name="password" id="password"><br>
        <label for ="password2">Type your password again: </label><input type="password" name="password2" id="password2"><br>
        <label for ="mail">Type your e-mail: </label><input type="email" name="mail" id="mail"><br>
    <input type="submit">
    </form>
{% endblock %}

templates/allarticles.html
{% extends 'home.html' %}
{% block content %}
    {% for a in article %}
        <h1>{{a.title}} by: {{ a.by_user.username}}</h1><br><br>
        <h2>{{ a.text }}</h2>

    {% endfor %}

{% endblock %}

templates/allstudios.html
{% extends 'home.html' %}
{% block content %}
    {% for s in studio %}
    <h1>{{ s.name }} :</h1>
        {% for g in s.game_set.all %}
            <h2>{{ g.name }}</h2>

        {% endfor %}
    {% endfor %}

{% endblock %}

templates/createpost.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
        {{ msg }}
        {{ form.as_p }}
    <input type="submit">
    </form>
{% endblock %}

templates/forum.html
{% extends 'home.html' %}
{% block content %}
    <a href="/gamecave/forum/addpost/">Dodaj post!</a>
    {% for p in posts %}
    <br><h3><a href="/gamecave/forum/{{p.id }}">{{ p.title }}</a>{{ p.user.username }} {{ p.date }} Liczba odpowiedzi:{{ p.post_answer_set.all.count }} <a href="/gamecave/forum/{{p.id }}">Odpowiedz</a></h3><br><h4>{{p.text}}</h4><br><br>
    {% endfor %}


{% endblock %}

templates/forumpost.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}

    <h2>{{ post.title }} by {{ post.user.username }} added {{ post.date }}</h2>
    <h3>{{ post.text }}</h3>
    answers:
    {{ form.as_p }}
    <input type="submit">
    {% for a in answers %}
    <h4>{{ a.user.username }} {{ a.date }}</h4>
        <h5>{{ a.text }}</h5>
    {% endfor %}
    </form>


{% endblock %}

templates/game.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
    <h3>{{ game.name }} {{ game.year }}</h3>
    <h4>{{ game.description }}<br><br> Studio: {{ game.studio.name }}</h4>
    {% if form %}
        Oceń tą grę!<br>
        Wybierz ocene:<br>{{ form.rate }}<br>Napisz komentarz!:<br>{{ form.reviews }}<br>
    <input type="submit"><br>
    {% endif %}
    {{ log_msg }}<br><br>
    Oceny naszych użytkowników:<br><br>
    {% for g in gamerating %}
        {{ forloop.counter }}. Rate: {{ g.rate }} by {{ g.user.username }}<br>{{ g.reviev }} <br><br>
    {% endfor %}
    </form>
{% endblock %}

templates/home.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GamersCave</title>
    <link rel="stylesheet" href="{% static 'GamersCave/style.css' %}" type="text/css"/>
    <script src="{% static 'GamersCave/time.js'%} "></script>


</head>
<body onload="timer()">

<div id ="container">

    <div class="rectangle">
        <a href="/" class="tilelink"><div id = logo>GamersCave</div></a>
        <div id  ="zegar">00:00:00</div>
        <div style="clear:both"></div>
    </div>

    <ul class="menu">
        <li><a href="/add_studio/">Dodaj studio</a></li>
        <li><a href=/all_studios/>Pokaz studia</a></li>
        <li><a href="/add_game/">Dodaj gre</a></li>
        <li><a href="/all_games/">Pokaz gry</a></li>
        <li><a href="/add_article/">Dodaj Artykul</a></li>
        <li><a href="/all_articles/">Pokaz Artykuly</a></li>
        <li><a href="/gamecave/forum/">Forum(dla zalogowanych)</a></li>
    </ul>
    <ul class="menu">
        <li><a href="/add_user/">Zarejestruj</a></li>
        <li><a href="/login/">Zaloguj</a></li>
        <li><a href="/logout/">Wyloguj</a></li>
    </ul>

        <h3 class="error">{{ msg }}</h3>
        <div class="template">
            {% block content %}
            {% endblock %}
        </div>

</div>
</body>
</html>

templates/login.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
        {{ msg }}<br>
        <label for ="username">Type your username: </label><input type="text" name="username" id="username"><br>
        <label for ="password">Type your password: </label><input type="password" name="password" id="password"><br>
        <input type="submit">
    </form>
{% endblock %}

templates/login2.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}
        {{ msg }}
        {{ form.as_p }}
    <input type="submit">
    </form>
{% endblock %}

templates/newarticle.html
{% extends 'home.html' %}
{% block content %}
    <form method="POST">{% csrf_token %}

        {{ form.as_p }}
    <input type="submit">
    </form>
{% endblock %}

templates/studio.html
{% extends 'home.html' %}
{% block content %}
    {{ studio.name }}
    {{ studio.is_active }}
{% endblock %}